version: 2

builds:
  - binary: watchducker
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - push.yaml.example

dockers_v2:
  - images:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.IMAGE_NAME }}"

    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"

    platforms:
      - linux/amd64
      - linux/arm64

    extra_files:
      - push.yaml.example
